//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SafinGlazkiSave
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductSale
    {
        public int ID { get; set; }

        public string ProductText
        {
            get
            {
                return Product.Title;
            }
        }
        public int AgentID { get; set; }
        public int ProductID { get; set; }
        public System.DateTime SaleDate { get; set; }
        public int ProductCount { get; set; }

        public decimal Stoimost
        {
            get
            {
                return ProductCount * Product.MinCostForAgent;
            }
        }

        public string TitleForBindingComboBox
        {
            get
            {
                return Product.Title;
            }
        }
        public virtual Agent Agent { get; set; }
        public virtual Product Product { get; set; }
    }
}
